services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: omop-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
      - ./api/main.py:/app/main.py
    environment:
      - DB_PATH=/app/data/omop.duckdb
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: omop-web
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped

volumes:
  data:
    driver: local